version: '3.8'

services:
  app:
    image: 127.0.0.1:5000/meuapp-pdf:latest
    ports:
      - "3001:3001"
    volumes:
      - temp:/app/temp
    environment:
      - NODE_ENV=production

volumes:
  temp:
    driver: local

