version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
    restart: unless-stopped 